Feature/storage
knoldus/Carpooling-Chain pull request #1
Opened 2021-07-06 19:33 UTC by Ayushi-knoldus

2021-07-15 07:37 UTC, aman2909verma requested changes

2021-07-15 07:37 UTC, aman2909verma commented on pallets/carpooling/src/lib.rs
> +	//pub type Something<T> = StorageValue<_, u32>;
remove this comment

2021-07-15 07:37 UTC, aman2909verma commented on pallets/carpooling/src/lib.rs
> +		/*/// An example dispatchable that may throw a custom error.
do not comment out this dispatch call, delete it instead

2021-07-15 07:37 UTC, aman2909verma commented on pallets/carpooling/src/lib.rs
> +    pub type Booking<T: Config> = StorageMap<_, Blake2_128Concat, CustomerOf<T>, DriverOf<T>>;
change this StorageMap to map from T::AccountId to T::AccountId

2021-07-16 09:13 UTC, aman2909verma approved these changes

2021-07-19 07:20 UTC, bishtpawan commented on pallets/carpooling/src/lib.rs
> +	type CustomerOf<T> = SCustomer<<T as frame_system::Config>::Hash>;
Please add documentation

2021-07-19 07:20 UTC, bishtpawan commented on pallets/carpooling/src/lib.rs
> +			//<Something<T>>::put(something);
please remove commented code

2021-07-19 07:21 UTC, bishtpawan commented
Raise PR for dev branch

2021-07-19 12:04 UTC, closed without merging