CC-SP4-101.8.3 updated cab loaction API
knoldus/Carpooling-Chain pull request #28
Opened 2021-08-30 09:11 UTC by ankit-mogha

What does this change do?
Added API for updating cab location

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?
CC -SP4- 101.8.3 - Polkadot API for update cab location.

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
Yes

Definition of Done:
- [ ] Is there >90% unit test code coverage?
- [ ] Does this PR add new dependencies? If so, please list out the same.
- [ ]  Will this feature require a new piece of infrastructure to be implemented?
- [x] Is there appropriate logging included?
- [x] Does the project compile ok?
- [x] Have Clippy violations been fixed?
- [x] Have Code is properly formatted?

2021-08-31 06:17 UTC, aman2909verma requested changes
do not push the idea folder and correct the code

2021-08-31 06:17 UTC, aman2909verma commented on app/src/index.js
> +                const updateCustLocation = api.tx.carpooling.updateCustomerLocation(15,{id: 15, name: "0x"+cust, location: [20,40]});
wrong parameters for the function

2021-08-31 06:42 UTC, aman2909verma requested changes

2021-08-31 06:42 UTC, aman2909verma commented on app/src/index.js
> +                const updateCustLocation = api.tx.carpooling.updateCustomerLocation(15,{id: 15, name: "0x"+cust, location: [20,40]});
wrong function called. call function to update cab location, not the customer.

2021-09-02 04:49 UTC, aman2909verma requested changes

2021-09-02 04:49 UTC, aman2909verma commented on app/src/index.js
> +                const updateCabLocation = api.tx.carpooling.updateCabLocation(15,{id: 15, location: [20,40]});
wrong parameters passed for the function

2021-09-02 04:49 UTC, aman2909verma commented on app/src/index.js
> +            let namePromise = digestMessage("Ankit Mogha");
digestMessage function not needed

2021-09-02 04:49 UTC, aman2909verma commented
do not push idea folder

2021-09-02 10:18 UTC, Ayushi-knoldus reviewed
remove extra files please

2021-09-06 14:14 UTC, aman2909verma approved these changes

2021-09-06 14:47 UTC, closed without merging