CC -SP4- 101.8.2 - Polkadot API for add cab
knoldus/Carpooling-Chain pull request #29
Opened 2021-08-31 05:05 UTC by Ayushi-knoldus

What does this change do?
Add a polkadot API to add new cab

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?
CC -SP4- 101.8.2 - Polkadot API for add cab

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
Yes

Definition of Done:

 - [ ] Is there >90% unit test code coverage?
 - [ ]  Does this PR add new dependencies? If so, please list out the same.
 - [ ] Will this feature require a new piece of infrastructure to be implemented?
 - [x] Is there appropriate logging included?
 - [x] Does the project compile ok?
 - [x] Have Clippy violations been fixed?
 - [x] Have Code is properly formatted?

2021-08-31 06:18 UTC, aman2909verma requested changes

2021-08-31 06:18 UTC, aman2909verma commented on app/src/index.js
> +                api.tx.carpooling.addNewCab(15,{id: 15, car_no: car_no , location: (20,40), price: 30 , destination:(40,20)});
submit the transaction

2021-09-03 06:27 UTC, aman2909verma requested changes

2021-09-03 06:27 UTC, aman2909verma commented on app/src/index.js
> +                const addCab = api.tx.carpooling.addNewCab(15,{id: 15, car_no: car_no , location: (20,40), price: 30 , destination:(40,20)});
use square brackets for tuples.

2021-09-05 02:27 UTC, ankit-mogha approved these changes

2021-09-06 11:50 UTC, aman2909verma approved these changes

2021-09-07 04:47 UTC, ankit-mogha commented
Please resolve merge conflicts.

2021-09-07 04:48 UTC, aman2909verma requested changes
Remove merge conflicts

2021-09-08 06:00 UTC, closed without merging