Add new customer dispatch call
knoldus/Carpooling-Chain pull request #3
Opened 2021-07-23 19:47 UTC by ankit-mogha

What does this change do?
add a dispatch call to add a new customer.

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need the window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?
AR-20: Publish compressed logs to Kafka topic.

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
Yes

Definition of Done:
- [ ] Is there >90% unit test code coverage?
- [ ] Does this PR add new dependencies? If so, please list out the same.
- [ ]  Will this feature require a new piece of infrastructure to be implemented?
- [x] Is there appropriate logging included?
- [x] Does the project compile ok?
- [x] Have Clippy violations been fixed?
- [x] Have Code is properly formatted?

2021-07-26 08:36 UTC, aman2909verma requested changes

2021-07-26 08:36 UTC, aman2909verma commented on pallets/carpooling/src/lib.rs
> +    pub type Booking<T: Config> = StorageMap<_, Blake2_128Concat, u32, T::AccountId>;
change T::AccountId to u32

2021-07-26 08:36 UTC, aman2909verma commented on pallets/carpooling/src/lib.rs
>          pub location: Hash,
make the location as tuple of (u32,u32)

2021-07-26 08:36 UTC, aman2909verma commented on pallets/carpooling/src/lib.rs
>          pub location: Hash,
make the location as tuple of (u32,u32)

2021-07-26 08:36 UTC, aman2909verma commented on pallets/carpooling/src/tests.rs
> -		assert_ok!(TemplateModule::do_something(Origin::signed(1), 42));
use Carpooling not TemplateModule in all test cases

2021-07-26 08:36 UTC, aman2909verma commented on pallets/carpooling/src/tests.rs
> +            location: "New Delhi".using_encoded(<Test as frame_system::Config>::Hashing::hash),
change location to a tuple in all test cases for exact location

2021-07-26 08:37 UTC, aman2909verma requested changes

2021-07-26 08:37 UTC, aman2909verma commented on pallets/carpooling/src/tests.rs
> +            TemplateModule::add_new_customer(Origin::signed(1), 42, new_cust),
use Carpooling not TemplateModule in all test cases

2021-07-26 14:55 UTC, aman2909verma approved these changes

2021-07-27 07:08 UTC, Ayushi-knoldus approved these changes

2021-07-27 07:26 UTC, bishtpawan commented on pallets/carpooling/src/lib.rs
> +        pub fn add_new_customer(
please add documentation

2021-07-27 07:27 UTC, bishtpawan commented on pallets/carpooling/src/lib.rs
> +            match <Customer<T>>::get(cust_id) {
please try to update flow

2021-07-27 08:16 UTC, closed without merging